/*

 CHERRY_SPRITE.C

 Tile Source File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 0

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

/* Start of tile array. */
unsigned char cherry_sprite[] =
{
  0x1E,0x1E,0x1F,0x11,0x3E,0x3E,0x60,0x60,
  0x98,0xF8,0xA4,0xFC,0x64,0x7C,0x18,0x18
};

/* End of CHERRY_SPRITE.C */
